insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (1, '0y85hnj', 'Rice-DuBuque', 'brand compelling e-business');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (2, '0t65xes', 'Toy LLC', 'empower global action-items');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (3, '9b55ngb', 'Schultz, Toy and Jerde', 'streamline plug-and-play schemas');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (4, '9e90egk', 'Schoen-Aufderhar', 'redefine cross-media methodologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (5, '3i91twu', 'Connelly-Hagenes', 'innovate B2C technologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (6, '2j73otk', 'Watsica LLC', 'matrix e-business niches');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (7, '9m40yqu', 'Zemlak, Casper and Hamill', 'evolve efficient ROI');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (8, '6d08nlj', 'Cassin-Schulist', 'envisioneer clicks-and-mortar markets');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (9, '6w17yol', 'Ortiz, Hackett and Anderson', 'harness one-to-one deliverables');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (10, '1j37wtu', 'Weissnat Group', 'leverage transparent solutions');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (11, '1y37zhd', 'Gleichner, Ritchie and Raynor', 'innovate innovative platforms');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (12, '6k77chy', 'Abernathy, Jacobson and Blick', 'seize ubiquitous applications');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (13, '4b50hkh', 'Lehner, Braun and Wyman', 'e-enable global e-commerce');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (14, '2m11jmw', 'Leuschke-Stanton', 'enhance web-enabled deliverables');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (15, '9s52bqb', 'Powlowski-Bogisich', 'transition frictionless channels');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (16, '9j06wqr', 'Bartoletti, Yost and Walker', 'brand strategic content');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (17, '8t94lat', 'Kohler-Bogisich', 'cultivate scalable models');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (18, '1g03jax', 'Hauck and Sons', 'aggregate cross-media channels');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (19, '5x92lly', 'Barton Inc', 'synthesize collaborative technologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (20, '3u25aum', 'Bogisich Group', 'reintermediate next-generation initiatives');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (21, '0v59cuf', 'Hoppe-Robel', 'e-enable out-of-the-box convergence');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (22, '5e97ght', 'Larkin LLC', 'engineer leading-edge deliverables');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (23, '4f87pyu', 'Grady-Kassulke', 'empower cutting-edge e-commerce');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (24, '5p96qxf', 'Altenwerth, O''Connell and Smith', 'strategize leading-edge action-items');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (25, '3s43kkn', 'Weissnat-Fahey', 'optimize robust relationships');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (26, '4a51vnn', 'Gutkowski, Kassulke and Dooley', 'morph plug-and-play communities');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (27, '2k07aph', 'Blanda, Shanahan and Gleichner', 'recontextualize bleeding-edge initiatives');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (28, '2b42yqi', 'Cole Inc', 'innovate leading-edge web-readiness');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (29, '5u06gut', 'Stark and Sons', 'deploy 24/7 networks');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (30, '9b88trm', 'Feest-Sanford', 'empower synergistic e-markets');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (31, '3t27cdb', 'Blick and Sons', 'utilize front-end e-tailers');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (32, '6r75aqz', 'Dooley-Pouros', 'architect impactful e-commerce');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (33, '5g68pip', 'Powlowski, Metz and Purdy', 'reinvent open-source initiatives');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (34, '8f81wak', 'Walker-Renner', 'maximize ubiquitous mindshare');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (35, '9c65urq', 'Shields Group', 'brand web-enabled applications');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (36, '4v43gzw', 'Jones and Sons', 'revolutionize granular methodologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (37, '3r91vkw', 'Hane, Leffler and Haley', 'expedite best-of-breed paradigms');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (38, '1q61wbe', 'Witting, Durgan and Hoppe', 'recontextualize open-source portals');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (39, '7e99cuk', 'Auer and Sons', 'enable enterprise technologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (40, '0x14eus', 'Kuhlman-Huels', 'streamline efficient portals');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (41, '4u06cpp', 'Stehr, Stamm and Muller', 'facilitate intuitive users');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (42, '4z96jno', 'Krajcik, Jacobi and Ebert', 'brand enterprise architectures');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (43, '2h51wtp', 'Batz Inc', 'grow B2C schemas');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (44, '3m35ojk', 'Schuster-Kovacek', 'embrace innovative systems');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (45, '6h17jjr', 'Kirlin-Volkman', 'expedite open-source paradigms');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (46, '9f45ozx', 'Bailey, Watsica and Corwin', 'empower ubiquitous experiences');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (47, '4d63dbl', 'Raynor-Kiehn', 'utilize value-added technologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (48, '0u61mep', 'Bruen-Beatty', 'incentivize front-end channels');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (49, '6z01grf', 'Vandervort Group', 'orchestrate interactive synergies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (50, '4q06hla', 'Harvey, Willms and Reynolds', 'disintermediate collaborative functionalities');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (51, '0i39yix', 'Zieme Inc', 'enhance B2C relationships');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (52, '5h71cnv', 'Botsford and Sons', 'harness B2C e-business');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (53, '7j00kum', 'Mertz and Sons', 'envisioneer vertical solutions');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (54, '7q19bjz', 'Mosciski-Bechtelar', 'synthesize best-of-breed niches');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (55, '2d46aia', 'Kohler LLC', 'redefine bricks-and-clicks relationships');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (56, '4c70hjl', 'Hoeger-Schmitt', 'seize one-to-one e-services');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (57, '7h11puw', 'Boyer and Sons', 'revolutionize user-centric infomediaries');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (58, '8x90nvp', 'Conroy, Wolf and Mills', 'extend cutting-edge metrics');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (59, '1g59ods', 'Kovacek, Volkman and Kshlerin', 'visualize wireless models');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (60, '7q81czc', 'Sipes-Kilback', 'iterate intuitive infomediaries');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (61, '4v38gxz', 'Barton-Frami', 'empower sticky functionalities');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (62, '9j76pgl', 'Fahey, Koch and Bayer', 'optimize intuitive interfaces');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (63, '5w20hla', 'Wolff, Harvey and Kassulke', 'maximize synergistic metrics');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (64, '1j32ydv', 'Keebler Group', 'mesh out-of-the-box mindshare');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (65, '8e87aqn', 'Jacobi and Sons', 'incubate web-enabled relationships');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (66, '6d14ycp', 'Champlin-Langosh', 'evolve mission-critical niches');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (67, '3t83pmf', 'Reichel, Towne and Collins', 'e-enable back-end paradigms');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (68, '6o68lnh', 'Friesen, Senger and Schamberger', 'repurpose extensible e-business');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (69, '5g71utn', 'Funk, Dickinson and Dickens', 'aggregate cross-platform experiences');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (70, '4g74plr', 'Russel-Spencer', 'grow efficient mindshare');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (71, '3z24yah', 'Ortiz LLC', 'orchestrate synergistic convergence');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (72, '6a32qik', 'Kohler LLC', 'streamline next-generation web services');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (73, '1g04nye', 'O''Connell Inc', 'revolutionize B2B ROI');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (74, '4p30yvj', 'Jenkins-Harber', 'deliver frictionless technologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (75, '2a87mkc', 'Gleason, Morar and Stiedemann', 'deploy impactful e-tailers');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (76, '5d43bjq', 'Stanton, Nitzsche and Schneider', 'harness end-to-end vortals');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (77, '7f87ixv', 'Effertz LLC', 'grow seamless eyeballs');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (78, '3k41nre', 'McDermott LLC', 'incubate front-end partnerships');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (79, '1g84nfl', 'Gusikowski-Durgan', 'revolutionize B2C systems');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (80, '8z71ndx', 'Kunde, Harris and Beahan', 'incentivize revolutionary schemas');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (81, '4v69kzo', 'Pouros, Luettgen and Reichert', 'extend scalable markets');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (82, '4u77qyl', 'Murazik, Batz and Hirthe', 'deploy strategic interfaces');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (83, '0c42uzi', 'Trantow, Fadel and Rohan', 'enable sticky systems');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (84, '6d45cgh', 'Hilll-Konopelski', 'repurpose impactful platforms');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (85, '9h97jjf', 'Harris Inc', 'seize front-end web-readiness');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (86, '9e03qfu', 'Gerhold, Ebert and Kihn', 'scale virtual convergence');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (87, '1o97qwl', 'Welch Group', 'exploit visionary architectures');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (88, '2v14goo', 'Wolff, Kilback and Grady', 'envisioneer seamless ROI');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (89, '6j83gvo', 'Cremin-Reilly', 'grow holistic deliverables');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (90, '8j35nil', 'McDermott and Sons', 'mesh real-time niches');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (91, '1b40cxy', 'West and Sons', 'target out-of-the-box markets');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (92, '0e10urv', 'Wisozk Group', 'leverage open-source methodologies');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (93, '1x75vwu', 'Bergstrom-Heller', 'generate frictionless supply-chains');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (94, '4v37feo', 'Baumbach and Sons', 'implement global supply-chains');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (95, '9u81igh', 'Ziemann, Hane and Cremin', 'innovate customized applications');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (96, '1u74wup', 'Zieme, Fritsch and Hoppe', 'envisioneer world-class content');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (97, '0a87hpe', 'Langworth-Borer', 'recontextualize ubiquitous infrastructures');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (98, '7f20sol', 'Ruecker LLC', 'utilize dynamic models');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (99, '6h59gbi', 'Tillman, Halvorson and Aufderhar', 'transform back-end channels');
insert into admin_re.editorial (editorial_id, clave, nombre, descripcion) values (100, '5n70pdv', 'Lesch LLC', 'matrix viral infrastructures');
